import { NextRequest } from 'next/server'
import { z } from 'zod'
import { AIService } from '@/lib/ai'
import { buildContext } from '@/lib/ai/conversation'
import { rateLimit } from '@/lib/rate-limit'
import { formatResearchContext, googleSearch, shouldAutoSearch } from '@/lib/web-search'
const ChatSchema=z.object({message:z.string().min(1).max(8000),history:z.array(z.object({role:z.enum(['user','assistant','system']),content:z.string().max(20000)})).max(40).optional(),conversationId:z.string().optional(),webSearch:z.boolean().optional()})
export const runtime='nodejs'
export async function POST(req:NextRequest){try{const ip=(req.headers.get('x-forwarded-for')||'anonymous').split(',')[0].trim();const rl=await rateLimit(`chat:${ip}`,30,60000);if(!rl.allowed)return new Response(JSON.stringify({error:'Rate limit exceeded. Please try again shortly.'}),{status:429,headers:{'Content-Type':'application/json'}});const parsed=ChatSchema.safeParse(await req.json());if(!parsed.success)return new Response(JSON.stringify({error:'Invalid request body'}),{status:400});const{message,history=[],webSearch}=parsed.data;const doSearch=!!webSearch||shouldAutoSearch(message);let sources:any[]=[];let researchContext='';if(doSearch){try{sources=await googleSearch(message,6,req.signal);if(sources.length)researchContext=formatResearchContext(sources)}catch(err){console.warn('[web-search]',err)}}const context=buildContext(history,message,researchContext);const stream=new ReadableStream({async start(controller){const encoder=new TextEncoder();try{const abortCtrl=new AbortController();req.signal.addEventListener('abort',()=>abortCtrl.abort());if(sources.length)controller.enqueue(encoder.encode(`data: ${JSON.stringify({webSearch:true,sources})}\n\n`));for await(const chunk of AIService.streamChat(context,abortCtrl.signal)){if(chunk.text)controller.enqueue(encoder.encode(`data: ${JSON.stringify({text:chunk.text})}\n\n`));if(chunk.done)break}controller.enqueue(encoder.encode('data: [DONE]\n\n'));controller.close()}catch(err:any){console.error('[chat] provider error:',err);const safe=err?.message?.includes('Custom Munyarwanda LLM')?err.message:'Munyarwanda AI is temporarily unavailable. Please try again.';controller.enqueue(encoder.encode(`data: ${JSON.stringify({error:safe})}\n\n`));controller.close()}}});return new Response(stream,{headers:{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'}})}catch(err){console.error('[chat]',err);return new Response(JSON.stringify({error:'Your request could not be completed.'}),{status:500,headers:{'Content-Type':'application/json'}})}}
